# comarison between Keras optimizers in ANN by keras library

## 1-class SGD: Gradient descent (with momentum) optimizer.

## 2-class Adagrad: Optimizer that implements the Adagrad algorithm.

## 3-class Adadelta: Optimizer that implements the Adadelta algorithm.

## 4-class RMSprop: Optimizer that implements the RMSprop algorithm.

## 5-class Adam: Optimizer that implements the Adam algorithm.

## 6-class Adamax: Optimizer that implements the Adamax algorithm.

## 7-class Nadam: Optimizer that implements the NAdam algorithm.

## 8-class AMSgrad: is a recent proposed improvement to Adam.

In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

from tensorflow import keras
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

In [2]:
dataset = pd.read_csv('Churn_Modelling.csv')
dataset.head()

RowNumber  CustomerId   Surname  CreditScore Geography  Gender  Age  \
0          1    15634602  Hargrave          619    France  Female   42   
1          2    15647311      Hill          608     Spain  Female   41   
2          3    15619304      Onio          502    France  Female   42   
3          4    15701354      Boni          699    France  Female   39   
4          5    15737888  Mitchell          850     Spain  Female   43   

   Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember  \
0       2       0.00              1          1               1   
1       1   83807.86              1          0               1   
2       8  159660.80              3          1               0   
3       1       0.00              2          0               0   
4       2  125510.82              1          1               1   

   EstimatedSalary  Exited  
0        101348.88       1  
1        112542.58       0  
2        113931.57       1  
3         93826.63       0  
4         79084.10       0

In [3]:
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 14 columns):
 #   Column           Non-Null Count  Dtype  
---  ------           --------------  -----  
 0   RowNumber        10000 non-null  int64  
 1   CustomerId       10000 non-null  int64  
 2   Surname          10000 non-null  object 
 3   CreditScore      10000 non-null  int64  
 4   Geography        10000 non-null  object 
 5   Gender           10000 non-null  object 
 6   Age              10000 non-null  int64  
 7   Tenure           10000 non-null  int64  
 8   Balance          10000 non-null  float64
 9   NumOfProducts    10000 non-null  int64  
 10  HasCrCard        10000 non-null  int64  
 11  IsActiveMember   10000 non-null  int64  
 12  EstimatedSalary  10000 non-null  float64
 13  Exited           10000 non-null  int64  
dtypes: float64(2), int64(9), object(3)
memory usage: 1.1+ MB


In [4]:
dataset.drop('Geography',axis=1,inplace=True)
dataset.drop('Gender',axis=1,inplace=True)

dataset.head()

RowNumber  CustomerId   Surname  CreditScore  Age  Tenure    Balance  \
0          1    15634602  Hargrave          619   42       2       0.00   
1          2    15647311      Hill          608   41       1   83807.86   
2          3    15619304      Onio          502   42       8  159660.80   
3          4    15701354      Boni          699   39       1       0.00   
4          5    15737888  Mitchell          850   43       2  125510.82   

   NumOfProducts  HasCrCard  IsActiveMember  EstimatedSalary  Exited  
0              1          1               1        101348.88       1  
1              1          0               1        112542.58       0  
2              3          1               0        113931.57       1  
3              2          0               0         93826.63       0  
4              1          1               1         79084.10       0

In [5]:
X = dataset.iloc[:, 3:11].values
y = dataset.iloc[:, 11].values

In [6]:
# Splitting the dataset into the Training set and Test set
from sklearn.model_selection import train_test_split
X_train, X_test, Y_train, Y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

In [7]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)


# 1-class SGD

In [8]:
# Initialising the ANN
classifier = Sequential()

# Adding the input layer and the first hidden layer
classifier.add(Dense(units = 6, kernel_initializer = 'uniform', activation = 'relu', input_dim = 8))

# Adding the second hidden layer
classifier.add(Dense(units = 6, kernel_initializer = 'uniform', activation = 'relu'))

# Adding the output layer
classifier.add(Dense(units = 1, kernel_initializer = 'uniform', activation = 'sigmoid'))

# Compiling the ANN
classifier.compile(optimizer='SGD', loss = 'binary_crossentropy', metrics = ['accuracy'])

# Fitting the ANN to the Training set
classifier.fit(X_train, Y_train, batch_size = 32, epochs = 100)

Epoch 1/100
250/250 [==============================] - 1s 999us/step - loss: 0.6515 - accuracy: 0.7901
Epoch 2/100
250/250 [==============================] - 0s 923us/step - loss: 0.5540 - accuracy: 0.7957
Epoch 3/100
250/250 [==============================] - 0s 975us/step - loss: 0.5221 - accuracy: 0.7974
Epoch 4/100
250/250 [==============================] - 0s 927us/step - loss: 0.5150 - accuracy: 0.7939
Epoch 5/100
250/250 [==============================] - 0s 939us/step - loss: 0.5067 - accuracy: 0.7977
Epoch 6/100
250/250 [==============================] - 0s 1ms/step - loss: 0.5040 - accuracy: 0.7985
Epoch 7/100
250/250 [==============================] - 0s 927us/step - loss: 0.5143 - accuracy: 0.7899
Epoch 8/100
250/250 [==============================] - 0s 919us/step - loss: 0.5066 - accuracy: 0.7956
Epoch 9/100
250/250 [==============================] - 0s 927us/step - loss: 0.4967 - accuracy: 0.8030
Epoch 10/100
250/250 [==============================] - 0s 991us/step - los

In [9]:
# Predicting the Test set results
y_pred = classifier.predict(X_test)
y_pred = (y_pred > 0.5) #greater than 0.50 on scale 0 to 1
# Making the Confusion Matrix
from sklearn.metrics import confusion_matrix,accuracy_score
cm = confusion_matrix(Y_test, y_pred)
cm

array([[1595,    0],
       [ 405,    0]], dtype=int64)

In [10]:
acc=accuracy_score(Y_test, y_pred)
print('accurcy of  model: ',acc *100,'%')

accurcy of  model:  79.75 %


# 2-class Adagrad

In [11]:
# Initialising the ANN
classifier = Sequential()

# Adding the input layer and the first hidden layer
classifier.add(Dense(units = 6, kernel_initializer = 'uniform', activation = 'relu', input_dim = 8))

# Adding the second hidden layer
classifier.add(Dense(units = 6, kernel_initializer = 'uniform', activation = 'relu'))

# Adding the output layer
classifier.add(Dense(units = 1, kernel_initializer = 'uniform', activation = 'sigmoid'))

# Compiling the ANN
classifier.compile(optimizer='Adagrad', loss = 'binary_crossentropy', metrics = ['accuracy'])

# Fitting the ANN to the Training set
classifier.fit(X_train, Y_train, batch_size = 32, epochs = 100)

Epoch 1/100
250/250 [==============================] - 1s 1ms/step - loss: 0.6898 - accuracy: 0.7834
Epoch 2/100
250/250 [==============================] - 0s 911us/step - loss: 0.6839 - accuracy: 0.7916
Epoch 3/100
250/250 [==============================] - 0s 939us/step - loss: 0.6801 - accuracy: 0.8039
Epoch 4/100
250/250 [==============================] - 0s 955us/step - loss: 0.6778 - accuracy: 0.7957
Epoch 5/100
250/250 [==============================] - 0s 939us/step - loss: 0.6754 - accuracy: 0.7983
Epoch 6/100
250/250 [==============================] - 0s 1ms/step - loss: 0.6733 - accuracy: 0.7983
Epoch 7/100
250/250 [==============================] - 0s 911us/step - loss: 0.6717 - accuracy: 0.7945
Epoch 8/100
250/250 [==============================] - 0s 939us/step - loss: 0.6695 - accuracy: 0.7995
Epoch 9/100
250/250 [==============================] - 0s 943us/step - loss: 0.6688 - accuracy: 0.7876
Epoch 10/100
250/250 [==============================] - 0s 1ms/step - loss: 0

In [12]:
# Predicting the Test set results
y_pred = classifier.predict(X_test)
y_pred = (y_pred > 0.5) #greater than 0.50 on scale 0 to 1
# Making the Confusion Matrix
from sklearn.metrics import confusion_matrix,accuracy_score
cm = confusion_matrix(Y_test, y_pred)
cm

array([[1595,    0],
       [ 405,    0]], dtype=int64)

In [13]:
acc=accuracy_score(Y_test, y_pred)
print('accurcy of  model: ',acc *100,'%')

accurcy of  model:  79.75 %


# 3-class Adadelta

In [14]:
# Initialising the ANN
classifier = Sequential()

# Adding the input layer and the first hidden layer
classifier.add(Dense(units = 6, kernel_initializer = 'uniform', activation = 'relu', input_dim = 8))

# Adding the second hidden layer
classifier.add(Dense(units = 6, kernel_initializer = 'uniform', activation = 'relu'))

# Adding the output layer
classifier.add(Dense(units = 1, kernel_initializer = 'uniform', activation = 'sigmoid'))

# Compiling the ANN
optimizer=keras.optimizers.Adadelta(learning_rate=0.001, rho=0.95)
classifier.compile(optimizer, loss = 'binary_crossentropy', metrics = ['accuracy'])

# Fitting the ANN to the Training set
classifier.fit(X_train, Y_train, batch_size = 32, epochs = 100)

Epoch 1/100
250/250 [==============================] - 1s 1ms/step - loss: 0.6931 - accuracy: 0.5457
Epoch 2/100
250/250 [==============================] - 0s 943us/step - loss: 0.6930 - accuracy: 0.8001
Epoch 3/100
250/250 [==============================] - 0s 979us/step - loss: 0.6929 - accuracy: 0.7966
Epoch 4/100
250/250 [==============================] - 0s 963us/step - loss: 0.6927 - accuracy: 0.7986
Epoch 5/100
250/250 [==============================] - 0s 1ms/step - loss: 0.6925 - accuracy: 0.7990
Epoch 6/100
250/250 [==============================] - 0s 951us/step - loss: 0.6924 - accuracy: 0.7944
Epoch 7/100
250/250 [==============================] - 0s 987us/step - loss: 0.6922 - accuracy: 0.7946
Epoch 8/100
250/250 [==============================] - 0s 943us/step - loss: 0.6920 - accuracy: 0.7969
Epoch 9/100
250/250 [==============================] - 0s 1ms/step - loss: 0.6918 - accuracy: 0.7977
Epoch 10/100
250/250 [==============================] - 0s 975us/step - loss: 0

In [15]:
# Predicting the Test set results
y_pred = classifier.predict(X_test)
y_pred = (y_pred > 0.5) #greater than 0.50 on scale 0 to 1
# Making the Confusion Matrix
from sklearn.metrics import confusion_matrix,accuracy_score
cm = confusion_matrix(Y_test, y_pred)
cm

array([[1595,    0],
       [ 405,    0]], dtype=int64)

In [16]:
acc=accuracy_score(Y_test, y_pred)
print('accurcy of  model: ',acc *100,'%')

accurcy of  model:  79.75 %


# 4-class RMSprop

In [17]:
# Initialising the ANN
classifier = Sequential()

# Adding the input layer and the first hidden layer
classifier.add(Dense(units = 6, kernel_initializer = 'uniform', activation = 'relu', input_dim = 8))

# Adding the second hidden layer
classifier.add(Dense(units = 6, kernel_initializer = 'uniform', activation = 'relu'))

# Adding the output layer
classifier.add(Dense(units = 1, kernel_initializer = 'uniform', activation = 'sigmoid'))

# Compiling the ANN
classifier.compile(optimizer='RMSprop', loss = 'binary_crossentropy', metrics = ['accuracy'])

# Fitting the ANN to the Training set
classifier.fit(X_train, Y_train, batch_size = 32, epochs = 100)

Epoch 1/100
250/250 [==============================] - 1s 1ms/step - loss: 0.6554 - accuracy: 0.7891
Epoch 2/100
250/250 [==============================] - 0s 999us/step - loss: 0.4765 - accuracy: 0.7940
Epoch 3/100
250/250 [==============================] - 0s 1ms/step - loss: 0.4531 - accuracy: 0.7928
Epoch 4/100
250/250 [==============================] - 0s 943us/step - loss: 0.4342 - accuracy: 0.8006
Epoch 5/100
250/250 [==============================] - 0s 959us/step - loss: 0.4268 - accuracy: 0.8001
Epoch 6/100
250/250 [==============================] - 0s 987us/step - loss: 0.4368 - accuracy: 0.7969
Epoch 7/100
250/250 [==============================] - 0s 1ms/step - loss: 0.4258 - accuracy: 0.8005
Epoch 8/100
250/250 [==============================] - 0s 1ms/step - loss: 0.4302 - accuracy: 0.8109
Epoch 9/100
250/250 [==============================] - 0s 1ms/step - loss: 0.4308 - accuracy: 0.8215
Epoch 10/100
250/250 [==============================] - 0s 1ms/step - loss: 0.4229 

In [18]:
# Predicting the Test set results
y_pred = classifier.predict(X_test)
y_pred = (y_pred > 0.5) #greater than 0.50 on scale 0 to 1
# Making the Confusion Matrix
from sklearn.metrics import confusion_matrix,accuracy_score
cm = confusion_matrix(Y_test, y_pred)
cm

array([[1553,   42],
       [ 279,  126]], dtype=int64)

In [19]:
acc=accuracy_score(Y_test, y_pred)
print('accurcy of  model: ',acc *100,'%')

accurcy of  model:  83.95 %


# 5-class Adam

In [20]:
# Initialising the ANN
classifier = Sequential()

# Adding the input layer and the first hidden layer
classifier.add(Dense(units = 6, kernel_initializer = 'uniform', activation = 'relu', input_dim = 8))

# Adding the second hidden layer
classifier.add(Dense(units = 6, kernel_initializer = 'uniform', activation = 'relu'))

# Adding the output layer
classifier.add(Dense(units = 1, kernel_initializer = 'uniform', activation = 'sigmoid'))

# Compiling the ANN
optimizer=keras.optimizers.Adam(learning_rate=0.001, beta_1=0.9,beta_2=0.999)

classifier.compile(optimizer, loss = 'binary_crossentropy', metrics = ['accuracy'])

# Fitting the ANN to the Training set
classifier.fit(X_train, Y_train, batch_size = 32, epochs = 100)

Epoch 1/100
250/250 [==============================] - 1s 1ms/step - loss: 0.6567 - accuracy: 0.7878
Epoch 2/100
250/250 [==============================] - 0s 991us/step - loss: 0.4557 - accuracy: 0.7968
Epoch 3/100
250/250 [==============================] - 0s 1ms/step - loss: 0.4500 - accuracy: 0.7868
Epoch 4/100
250/250 [==============================] - 0s 967us/step - loss: 0.4449 - accuracy: 0.7955
Epoch 5/100
250/250 [==============================] - 0s 1ms/step - loss: 0.4385 - accuracy: 0.7916
Epoch 6/100
250/250 [==============================] - 0s 963us/step - loss: 0.4308 - accuracy: 0.7977
Epoch 7/100
250/250 [==============================] - 0s 999us/step - loss: 0.4214 - accuracy: 0.8064
Epoch 8/100
250/250 [==============================] - 0s 971us/step - loss: 0.4253 - accuracy: 0.8000
Epoch 9/100
250/250 [==============================] - 0s 1ms/step - loss: 0.4176 - accuracy: 0.8102
Epoch 10/100
250/250 [==============================] - 0s 955us/step - loss: 0.4

In [21]:
# Predicting the Test set results
y_pred = classifier.predict(X_test)
y_pred = (y_pred > 0.5) #greater than 0.50 on scale 0 to 1
# Making the Confusion Matrix
from sklearn.metrics import confusion_matrix,accuracy_score
cm = confusion_matrix(Y_test, y_pred)
cm

array([[1555,   40],
       [ 248,  157]], dtype=int64)

In [22]:
acc=accuracy_score(Y_test, y_pred)
print('accurcy of  model: ',acc *100,'%')

accurcy of  model:  85.6 %


# 6-class Adamax

In [23]:
# Initialising the ANN
classifier = Sequential()

# Adding the input layer and the first hidden layer
classifier.add(Dense(units = 6, kernel_initializer = 'uniform', activation = 'relu', input_dim = 8))

# Adding the second hidden layer
classifier.add(Dense(units = 6, kernel_initializer = 'uniform', activation = 'relu'))

# Adding the output layer
classifier.add(Dense(units = 1, kernel_initializer = 'uniform', activation = 'sigmoid'))

# Compiling the ANN

classifier.compile(optimizer='Adamax', loss = 'binary_crossentropy', metrics = ['accuracy'])

# Fitting the ANN to the Training set
classifier.fit(X_train, Y_train, batch_size = 32, epochs = 100)

Epoch 1/100
250/250 [==============================] - 1s 1ms/step - loss: 0.6752 - accuracy: 0.7891
Epoch 2/100
250/250 [==============================] - 0s 1ms/step - loss: 0.5691 - accuracy: 0.7857
Epoch 3/100
250/250 [==============================] - 0s 1ms/step - loss: 0.4693 - accuracy: 0.7929: 0s - loss: 0.4739 - accuracy: 0.
Epoch 4/100
250/250 [==============================] - 0s 1ms/step - loss: 0.4565 - accuracy: 0.7888
Epoch 5/100
250/250 [==============================] - 0s 975us/step - loss: 0.4476 - accuracy: 0.7953
Epoch 6/100
250/250 [==============================] - 0s 955us/step - loss: 0.4588 - accuracy: 0.7867
Epoch 7/100
250/250 [==============================] - 0s 983us/step - loss: 0.4423 - accuracy: 0.7910
Epoch 8/100
250/250 [==============================] - 0s 1ms/step - loss: 0.4317 - accuracy: 0.7975
Epoch 9/100
250/250 [==============================] - 0s 999us/step - loss: 0.4413 - accuracy: 0.7972
Epoch 10/100
250/250 [===========================

In [24]:
# Predicting the Test set results
y_pred = classifier.predict(X_test)
y_pred = (y_pred > 0.5) #greater than 0.50 on scale 0 to 1
# Making the Confusion Matrix
from sklearn.metrics import confusion_matrix,accuracy_score
cm = confusion_matrix(Y_test, y_pred)
cm

array([[1553,   42],
       [ 279,  126]], dtype=int64)

In [25]:
acc=accuracy_score(Y_test, y_pred)
print('accurcy of  model: ',acc *100,'%')

accurcy of  model:  83.95 %


# 7-class Nadam

In [26]:
# Initialising the ANN
classifier = Sequential()

# Adding the input layer and the first hidden layer
classifier.add(Dense(units = 6, kernel_initializer = 'uniform', activation = 'relu', input_dim = 8))

# Adding the second hidden layer
classifier.add(Dense(units = 6, kernel_initializer = 'uniform', activation = 'relu'))

# Adding the output layer
classifier.add(Dense(units = 1, kernel_initializer = 'uniform', activation = 'sigmoid'))

# Compiling the ANN

classifier.compile(optimizer='Nadam', loss = 'binary_crossentropy', metrics = ['accuracy'])

# Fitting the ANN to the Training set
classifier.fit(X_train, Y_train, batch_size = 32, epochs = 100)

Epoch 1/100
250/250 [==============================] - 1s 1ms/step - loss: 0.6346 - accuracy: 0.7843
Epoch 2/100
250/250 [==============================] - 0s 1ms/step - loss: 0.4463 - accuracy: 0.7971
Epoch 3/100
250/250 [==============================] - 0s 1ms/step - loss: 0.4530 - accuracy: 0.7841
Epoch 4/100
250/250 [==============================] - 0s 1ms/step - loss: 0.4357 - accuracy: 0.7955
Epoch 5/100
250/250 [==============================] - 0s 1ms/step - loss: 0.4336 - accuracy: 0.7954
Epoch 6/100
250/250 [==============================] - 0s 1ms/step - loss: 0.4274 - accuracy: 0.7974
Epoch 7/100
250/250 [==============================] - 0s 1ms/step - loss: 0.4208 - accuracy: 0.8068
Epoch 8/100
250/250 [==============================] - 0s 1ms/step - loss: 0.4272 - accuracy: 0.8238
Epoch 9/100
250/250 [==============================] - 0s 1ms/step - loss: 0.4333 - accuracy: 0.8181
Epoch 10/100
250/250 [==============================] - 0s 1ms/step - loss: 0.4060 - accura

In [27]:
# Predicting the Test set results
y_pred = classifier.predict(X_test)
y_pred = (y_pred > 0.5) #greater than 0.50 on scale 0 to 1
# Making the Confusion Matrix
from sklearn.metrics import confusion_matrix,accuracy_score
cm = confusion_matrix(Y_test, y_pred)
cm

array([[1553,   42],
       [ 281,  124]], dtype=int64)

In [28]:
acc=accuracy_score(Y_test, y_pred)
print('accurcy of  model: ',acc *100,'%')

accurcy of  model:  83.85000000000001 %


#  8-class AMSgrad: is a recent proposed improvement to Adam

In [29]:
# Initialising the ANN
classifier = Sequential()

# Adding the input layer and the first hidden layer
classifier.add(Dense(units = 6, kernel_initializer = 'uniform', activation = 'relu', input_dim = 8))

# Adding the second hidden layer
classifier.add(Dense(units = 6, kernel_initializer = 'uniform', activation = 'relu'))

# Adding the output layer
classifier.add(Dense(units = 1, kernel_initializer = 'uniform', activation = 'sigmoid'))

# Compiling the ANN
optimizer=keras.optimizers.Adam(amsgrad=True)

classifier.compile(optimizer, loss = 'binary_crossentropy', metrics = ['accuracy'])

# Fitting the ANN to the Training set
classifier.fit(X_train, Y_train, batch_size = 32, epochs = 100)

Epoch 1/100
250/250 [==============================] - 1s 995us/step - loss: 0.6452 - accuracy: 0.7974
Epoch 2/100
250/250 [==============================] - 0s 1ms/step - loss: 0.4415 - accuracy: 0.8003
Epoch 3/100
250/250 [==============================] - 0s 1ms/step - loss: 0.4430 - accuracy: 0.7936
Epoch 4/100
250/250 [==============================] - 0s 1ms/step - loss: 0.4450 - accuracy: 0.7945
Epoch 5/100
250/250 [==============================] - 0s 1ms/step - loss: 0.4329 - accuracy: 0.8008
Epoch 6/100
250/250 [==============================] - 0s 1ms/step - loss: 0.4304 - accuracy: 0.7983
Epoch 7/100
250/250 [==============================] - 0s 1ms/step - loss: 0.4246 - accuracy: 0.8027
Epoch 8/100
250/250 [==============================] - 0s 971us/step - loss: 0.4293 - accuracy: 0.7928
Epoch 9/100
250/250 [==============================] - 0s 999us/step - loss: 0.4172 - accuracy: 0.8230
Epoch 10/100
250/250 [==============================] - 0s 1ms/step - loss: 0.4277 - 

In [30]:
# Predicting the Test set results
y_pred = classifier.predict(X_test)
y_pred = (y_pred > 0.5) #greater than 0.50 on scale 0 to 1
# Making the Confusion Matrix
from sklearn.metrics import confusion_matrix,accuracy_score
cm = confusion_matrix(Y_test, y_pred)
cm

array([[1556,   39],
       [ 285,  120]], dtype=int64)

In [31]:
acc=accuracy_score(Y_test, y_pred)
print('accurcy of  model: ',acc *100,'%')

accurcy of  model:  83.8 %


# the best accurcy by adam optimizers in this data